"""upgrade table request4

Revision ID: e242b02e8a05
Revises: 6c98362c7567
Create Date: 2023-11-28 17:43:25.116609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e242b02e8a05'
down_revision: Union[str, None] = '6c98362c7567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requests')
    op.drop_column('users', 'quantity_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quantity_requests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('requests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
