"""upgrade table request

Revision ID: 5afddfc6ecde
Revises: 0ed9c8d9d6bd
Create Date: 2023-11-28 15:24:01.043634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afddfc6ecde'
down_revision: Union[str, None] = '0ed9c8d9d6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_request', sa.String(), nullable=False),
    sa.Column('owner_request', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_request'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('requests')
    # ### end Alembic commands ###
