"""last_request

Revision ID: 0ed9c8d9d6bd
Revises: 3defd0f4da98
Create Date: 2023-11-28 14:33:00.295402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed9c8d9d6bd'
down_revision: Union[str, None] = '3defd0f4da98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_request', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_request')
    # ### end Alembic commands ###
