"""upgrade users

Revision ID: 3defd0f4da98
Revises: 53c28033527f
Create Date: 2023-11-28 14:29:30.412422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3defd0f4da98'
down_revision: Union[str, None] = '53c28033527f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quantity_requests', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_three_request', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_three_request')
    op.drop_column('users', 'quantity_requests')
    # ### end Alembic commands ###
