"""upgrade table request5

Revision ID: 8bddde2aaf30
Revises: e242b02e8a05
Create Date: 2023-11-28 17:50:43.319729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bddde2aaf30'
down_revision: Union[str, None] = 'e242b02e8a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_request', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
