"""add answer request

Revision ID: 2f67a19f2348
Revises: 8bddde2aaf30
Create Date: 2023-11-29 13:14:46.661153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f67a19f2348'
down_revision: Union[str, None] = '8bddde2aaf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('answer_request', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'answer_request')
    # ### end Alembic commands ###
